# this is where we can add the sql db information.
version: '3'
services:

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
          - "5438:5432"
    volumes:
      - db-data:/demo

  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    build:
      context: backend
      dockerfile: ./backend.dockerfile
    volumes:
      - ./backend/app:/build/app
    ports:
      - 8000:80
    depends_on:
      - db

volumes:
  db-data:
